// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CountItemController from "./count_item_controller"
application.register("count-item", CountItemController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import UpdateFormController from "./update_form_controller"
application.register("update-form", UpdateFormController)
